# Generated by Django 4.2.10 on 2024-04-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_billing_address_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ref_code',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
