# Generated by Django 4.2.10 on 2024-05-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_billing_address_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='OrderItemsQty',
            field=models.CharField(default=50, max_length=500),
            preserve_default=False,
        ),
    ]
