# Generated by Django 4.2.10 on 2024-05-31 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_order_orderitemsqty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='OrderItemsQty',
        ),
    ]
